server {
    listen 8080;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    if ($http_x_origin_secret != "${ORIGIN_SECRET}") {
        return 403;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
